<a href="https://colab.research.google.com/github/aadi-kanwar/Neural-Network-Deep-Learning/blob/main/Exp_3_FNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder, StandardScaler

In [24]:
# Load the Iris Dataset

iris = load_iris()
X = iris.data
y = iris.target.reshape(-1,1) # Labels

# OneHot Encoder
encoder = OneHotEncoder(sparse=False)
y = encoder.fit_transform(y)

# Standardize the features
scaler = StandardScaler()
X = scaler.fit_transform(X)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


In [12]:
# FNN
model = Sequential()

# Input Layer -> Hidden Layer (8 neurons, activation: relu)
model.add(Dense(8, input_shape=(4,), activation='relu'))

# Hidden Layer -> Output Layer (3 neurons, activation: softmax)
model.add(Dense(3, activation='softmax'))

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [13]:
# Compile the Model
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [21]:
# Train the Model
model.fit(X_train, y_train, epochs=50, batch_size=5, verbose=1)

Epoch 1/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9851 - loss: 0.0585
Epoch 2/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9813 - loss: 0.0538
Epoch 3/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9952 - loss: 0.0430
Epoch 4/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9772 - loss: 0.0450
Epoch 5/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9662 - loss: 0.0664
Epoch 6/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9869 - loss: 0.0444
Epoch 7/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9801 - loss: 0.0606
Epoch 8/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9767 - loss: 0.0736
Epoch 9/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9687 - loss: 0.0731 
Epoch 10/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.9916 - loss: 0.0634 
Epoch 11/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - accuracy: 0.9866 - loss: 0.0623
Epoch 12/50
24/24 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.9630 - 

In [22]:
# Evaluate the model

loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print(f"Loss: {loss}, Accuracy: {accuracy}")

Loss: 0.04842395707964897, Accuracy: 1.0


In [23]:
# Make Predictions

predictions = model.predict(X_test)
print(predictions)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step
[[2.1169531e-04 9.8570538e-01 1.4082924e-02]
 [9.9958044e-01 4.1943949e-04 1.6877654e-07]
 [8.1193076e-13 2.0739235e-06 9.9999791e-01]
 [4.3901920e-04 9.3776119e-01 6.1799724e-02]
 [8.2435523e-05 9.3202931e-01 6.7888327e-02]
 [9.9825519e-01 1.7440505e-03 7.4557289e-07]
 [4.6820887e-03 9.9370879e-01 1.6090054e-03]
 [2.1885546e-06 1.2926174e-02 9.8707163e-01]
 [1.4386677e-06 6.3649070e-01 3.6350778e-01]
 [3.5275272e-04 9.9668664e-01 2.9606603e-03]
 [1.1272006e-04 1.6649456e-01 8.3339268e-01]
 [9.9961895e-01 3.8019125e-04 9.0076043e-07]
 [9.9962729e-01 3.7262167e-04 1.3949486e-07]
 [9.9965012e-01 3.4900766e-04 7.9169894e-07]
 [9.9994332e-01 5.6511988e-05 6.8833678e-08]
 [3.4630008e-03 9.7921348e-01 1.7323568e-02]
 [3.1334444e-08 4.2395142e-04 9.9957603e-01]
 [1.3528613e-04 9.9754697e-01 2.3176800e-03]
 [3.7530065e-04 9.7239256e-01 2.7231969e-02]
 [7.1043260e-09 2.7481734e-04 9.9972522e-01]
 [9.9976969e-01 2.2955907e-04 8.3748358e-07]
 [1.2241465e-04 2